### PR TITLE
Request to merge udpated code with master

### PR DESCRIPTION
**Pull request by rajeshvidyut**
- [ ] Implement session expiry, input validation, and retry logic
- [ ] Add forced logout on session expiry, improve validation, and update styles

### CODE REVIEW

**Review by JohnSundarrajJSR — APPROVED** [review]
Im fine with the code review, next we have to containerize with our Docker starter-kit (kickstart-docker).

**Comment by JohnSundarrajJSR** [comment]
@rajeshvidyut Ive squashed and merged with master, as of now deleting the development branch. Next time, pull from master and create new development branch. Thank you.

**Comment by rajeshvidyut** [comment]
Hi John,

Yeah sry I forgot to create new branch from master. Will do it next time..




Thanks & Regards,

Rajesh . D
+91 95660-19013
Chennai: 600096

**Comment by rajeshvidyut** [comment]
Hi John,


Will create a Branch and test for it, and then will raise a request for
docker from new branch.




Thanks & Regards,

Rajesh . D
+91 95660-19013
Chennai: 600096

**Pull request merged**
